In [3]:
import pandas as pd
ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
ser

a    1
b    2
c    3
dtype: int64

import pandas as pd
pd.Series([1, 2, 3])

In [4]:
pd.Series([1, 2, 3])

0    1
1    2
2    3
dtype: int64

In [18]:
ser.loc["b"]

np.int64(2)

In [19]:
ser["b"]

np.int64(2)

In [20]:
ser.loc["b":"c"]

b    2
c    3
dtype: int64

In [21]:
ser.loc[["a","c"]]

a    1
c    3
dtype: int64

In [22]:
ser.iloc[1]

np.int64(2)

In [23]:
ser.iloc[1:3]

b    2
c    3
dtype: int64

In [24]:
ser.loc[[True, False, True]]

a    1
c    3
dtype: int64

In [25]:
ser != 2

a     True
b    False
c     True
dtype: bool

In [26]:
ser.loc[ser != 2]

a    1
c    3
dtype: int64

In [27]:
import pandas as pd
df = pd.DataFrame(
 [[1, 10, 100], [2, 20, 200], [3, 30, 300]],
 index=["r1", "r2", "r3"],
 columns=["c1", "c2", "c3"],
)
df

    c1  c2   c3
r1   1  10  100
r2   2  20  200
r3   3  30  300

In [28]:
df.loc["r2", "c2"]

np.int64(20)

In [29]:
df.loc["r2", :]

c1      2
c2     20
c3    200
Name: r2, dtype: int64

In [30]:
df.loc[:, "c2"]

r1    10
r2    20
r3    30
Name: c2, dtype: int64

In [31]:
df.loc[["r1", "r3"], "c2":"c3"]

    c2   c3
r1  10  100
r3  30  300

In [32]:
df.iloc[1:3, [0, 2]]

    c1   c3
r2   2  200
r3   3  300

In [33]:
df["c2"]

r1    10
r2    20
r3    30
Name: c2, dtype: int64

In [34]:
df > 10

       c1     c2    c3
r1  False  False  True
r2  False   True  True
r3  False   True  True

In [35]:
df.loc[df["c2"] > 10]

    c1  c2   c3
r2   2  20  200
r3   3  30  300

In [36]:
df.loc[(df["c1"] > 1) & (df["c3"] < 300)]

    c1  c2   c3
r2   2  20  200

In [37]:
from urllib.parse import urljoin
import pandas as pd
base_url = "https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/"
anime_csv = urljoin(base_url, "anime.csv")
df = pd.read_csv(anime_csv)
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [38]:
df = pd.read_csv(anime_csv, index_col=0)
df.head()

,name,genre,type,episodes,rating,members
anime_id,,,,,,
32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [39]:
df = pd.read_csv(anime_csv, dtype={"members": float})
df.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes     object
rating      float64
members     float64
dtype: object

In [40]:
anime_stock_price_csv = urljoin(base_url, "anime_stock_price.csv")
df = pd.read_csv(anime_stock_price_csv, parse_dates=["Date"])
df.dtypes

Date              datetime64[ns]
TOEI ANIMATION           float64
IG Port                  float64
dtype: object

In [57]:
anime_tsv = urljoin(base_url, "anime.tsv")
df = pd.read_csv(anime_tsv, sep="\t")
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [42]:
# openpyxl（Excelを扱うためのライブラリ）をインストールする
!pip install openpyxl
# Excelファイルの読み込み
anime_xlsx = urljoin(base_url, "anime.xlsx")
df = pd.read_excel(anime_xlsx)
df.head()

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
2,28851,Koe no Katachi,"Drama, School, Shounen",Movie,1,9.05,102733
3,199,Sen to Chihiro no Kamikakushi,"Adventure, Drama, Supernatural",Movie,1,8.93,466254
4,12355,Ookami Kodomo no Ame to Yuki,"Fantasy, Slice of Life",Movie,1,8.84,226193

In [44]:
df = pd.read_excel(anime_xlsx, sheet_name='TV')
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
1,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
2,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
3,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
4,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351

In [45]:
# lxml（xmlやhtmlを扱うためのライブラリ）をインストールする
!pip install lxml
# HTMLファイルの読み込み
url = "https://docs.python.org/3/py-modindex.html"
tables = pd.read_html(url, index_col=1)
tables[0].loc[:, 1:].dropna().head(10) # 1番目のDataFrameから空の列と欠損値を除外

Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.3)

                                                               2
1
__future__                          Future statement definitions
__main__       The environment where top-level code is run. C...
_thread                                 Low-level threading API.
_tkinter       A binary module that contains the low-level in...
abc              Abstract base classes according to :pep:`3119`.
aifc                               Deprecated:  Removed in 3.13.
annotationlib        Functionality for introspecting annotations
argparse       Command-line option and argument parsing library.
array          Space efficient arrays of uniformly typed nume...
ast               Abstract Syntax Tree classes and manipulation.

In [48]:
# 列ごとの平均値を算出
from urllib.parse import urljoin
import pandas as pd
base_url = (
 "https://raw.githubusercontent.com/practical-jupyter/sample-data/master/anime/"
)
anime_master_csv = urljoin(base_url, "anime_master.csv")
df = pd.read_csv(anime_master_csv)
# 列ごとの平均値を算出
df.mean(numeric_only=True)

anime_id    14055.982035
episodes       13.939156
rating          6.507956
members     18924.950769
dtype: float64

In [49]:
# Series の合計値を算出
df["members"].sum()

np.int64(190668879)

In [50]:
df.describe().round(1)

       anime_id  episodes   rating    members
count   10075.0   10075.0  10075.0    10075.0
mean    14056.0      13.9      6.5    18925.0
std     11294.9      50.8      1.1    57117.5
min         1.0       1.0      1.7       12.0
25%      3431.0       1.0      5.9      177.0
50%     10526.0       1.0      6.6     1227.0
75%     24438.0      13.0      7.3    10254.0
max     34519.0    1818.0     10.0  1013917.0

In [51]:
df.describe(percentiles=[0.1, 0.9]).round(1)

       anime_id  episodes   rating    members
count   10075.0   10075.0  10075.0    10075.0
mean    14056.0      13.9      6.5    18925.0
std     11294.9      50.8      1.1    57117.5
min         1.0       1.0      1.7       12.0
10%      1259.4       1.0      5.1       74.0
50%     10526.0       1.0      6.6     1227.0
90%     31190.0      37.0      7.8    47587.6
max     34519.0    1818.0     10.0  1013917.0

In [52]:
df = pd.read_csv(anime_master_csv)
df[["genre", "type"]].describe()

         genre   type
count    10075  10075
unique    2735      6
top     Comedy     TV
freq       500   3330

In [54]:
!jupyter nbconvert --to html "/g26014nk_第二回.ipynb"

[NbConvertApp] Converting notebook /g26014nk_第二回.ipynb to html
[NbConvertApp] Writing 387955 bytes to /g26014nk_第二回.html